name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Run with qemu
    runs-on: ubuntu-24.04
    steps:
      - name: Repo clone
        uses: actions/checkout@v4

      - name: APT
        run: |
          ls -l /etc/apt/sources.list.d/
          cat /etc/apt/sources.list.d/ubuntu.sources
          sudo apt-get update
          cat /etc/apt/apt-mirrors.txt
          sudo apt-get install qemu-system-x86 mtools

      - name: Prepare
        run: |
          zstd -d < caldera-minimal-fat16.raw.zst > caldera.raw
          echo "drive x: file=\"$PWD/caldera.raw\" offset=32256" > ~/.mtoolsrc
          ./prep.sh

      - name: Run it
        run: |
	  mcopy X:bash/0build/config.log .
	  mcopy X:bash/0build/configure.org .

      - name:  artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bshbin
          path: |
            config.log
	    configure.org
